
CREATE TABLE b01_paciente (
    b01_id INTEGER DEFAULT 0 NOT NULL,
    b01_nome TEXT DEFAULT '' NOT NULL,
    b01_datanascimento DATE DEFAULT '1900-01-01' NOT NULL,
    b01_sexo INTEGER DEFAULT 0 NOT NULL,
    b01_anosaproximados INTEGER DEFAULT 0 NOT NULL,
    b01_e_enderezo TEXT DEFAULT '' NOT NULL,
    b01_e_coabitantes TEXT DEFAULT '' NOT NULL,
    b01_e_pessoacontacto TEXT DEFAULT '' NOT NULL,
    b01_e_aguapotavel INTEGER DEFAULT 0 NOT NULL, -- Representa un INTEGEReano (0 = false, 1 = true)
    b01_e_latrina INTEGER DEFAULT 0 NOT NULL,     -- Representa un INTEGEReano
    b01_e_higienedomestica INTEGER DEFAULT 0 NOT NULL, -- Representa un INTEGEReano
    b01_e_mosquiteira INTEGER DEFAULT 0 NOT NULL,      -- Representa un INTEGEReano
    b01_e_usana INTEGER DEFAULT 0 NOT NULL,            -- Representa un INTEGEReano
    b01_e_mosquiteira_pais INTEGER DEFAULT 0 NOT NULL, -- Representa un INTEGEReano
    b01_e_usana_pais INTEGER DEFAULT 0 NOT NULL,       -- Representa un INTEGEReano
    b01_e_mosquiteira_nenos INTEGER DEFAULT 0 NOT NULL,-- Representa un INTEGEReano
    b01_e_usana_nenos INTEGER DEFAULT 0 NOT NULL,      -- Representa un INTEGEReano
    b01_e_aguatratada INTEGER DEFAULT 0 NOT NULL,      -- Representa un INTEGEReano
    b01_e_animaisdomesticos INTEGER DEFAULT 0 NOT NULL,
    b01_e_numero_irmaos INTEGER DEFAULT 0 NOT NULL,
    CONSTRAINT pk_b01 PRIMARY KEY (b01_id)
);

CREATE UNIQUE INDEX uk_b01 ON b01_paciente (b01_nome, b01_datanascimento, b01_sexo, b01_anosaproximados);


CREATE TABLE b03_historias_adulto (
    b03_b01_id INTEGER DEFAULT 0 NOT NULL,
    b03_alergias TEXT DEFAULT '' NOT NULL,
    b03_dataapertura DATE DEFAULT '1900-01-01' NOT NULL,
    b03_ha_diabete INTEGER DEFAULT 0 NOT NULL,          -- Representa un INTEGEReano (0 = false, 1 = true)
    b03_ha_tratamientodiabete TEXT DEFAULT '' NOT NULL,
    b03_ha_hepatite INTEGER DEFAULT 0 NOT NULL,         -- Representa un INTEGEReano
    b03_ha_tipohepatite TEXT DEFAULT '' NOT NULL,
    b03_ha_tratamientohepatite TEXT DEFAULT '' NOT NULL,
    b03_ha_vih INTEGER DEFAULT 0 NOT NULL,              -- Representa un INTEGEReano
    b03_ha_tratamientovih TEXT DEFAULT '' NOT NULL,
    b03_ha_outrasdoenzas TEXT DEFAULT '' NOT NULL,
    b03_ha_deficiencias TEXT DEFAULT '' NOT NULL,
    b03_ha_conflictos TEXT DEFAULT '' NOT NULL,
    b03_ha_profesion TEXT DEFAULT '' NOT NULL,
    b03_ha_numerofillos INTEGER DEFAULT 0 NOT NULL,
    b03_vi_aguapotavel INTEGER DEFAULT 0 NOT NULL,      -- Representa un INTEGEReano
    b03_vi_latrina INTEGER DEFAULT 0 NOT NULL,          -- Representa un INTEGEReano
    b03_vi_higienedomestica INTEGER DEFAULT 0 NOT NULL, -- Representa un INTEGEReano
    b03_vi_animaisdomesticos INTEGER DEFAULT 0 NOT NULL,
    b03_vi_mosquiteira INTEGER DEFAULT 0 NOT NULL,      -- Representa un INTEGEReano
    b03_vi_usanamosquiteira INTEGER DEFAULT 0 NOT NULL, -- Representa un INTEGEReano
    b03_vi_controlsanitario INTEGER DEFAULT 0 NOT NULL, -- Representa un INTEGEReano
    b03_ef_peso INTEGER DEFAULT 0 NOT NULL,
    b03_ef_altura INTEGER DEFAULT 0 NOT NULL,
    b03_ef_temperatura INTEGER DEFAULT 0 NOT NULL,
    b03_ef_perimetroabdominal INTEGER DEFAULT 0 NOT NULL,
    b03_ef_imc INTEGER DEFAULT 0 NOT NULL,
    b03_ef_consciencia TEXT DEFAULT '' NOT NULL,
    b03_ef_glucemiacapilar TEXT DEFAULT '' NOT NULL,
    b03_ef_fc TEXT DEFAULT '' NOT NULL,
    b03_ef_fr TEXT DEFAULT '' NOT NULL,
    CONSTRAINT pk_b03 PRIMARY KEY (b03_b01_id),
    CONSTRAINT fk_b03_b01 FOREIGN KEY (b03_b01_id) REFERENCES b01_paciente(b01_id) ON DELETE CASCADE
);

CREATE TABLE b04_historias_embarazada (
    b04_b01_id INTEGER DEFAULT 0 NOT NULL,
    b04_alergias TEXT DEFAULT '' NOT NULL,
    b04_dataapertura DATE DEFAULT '1900-01-01' NOT NULL,
    b04_he_datapasadamestruacion DATE NULL,
    b04_he_dataprobableparto DATE NULL,
    b04_he_numeroirmaosmortos INTEGER DEFAULT 0 NOT NULL,
    b04_he_numeroparto INTEGER DEFAULT 0 NOT NULL,
    b04_he_numeroabortos INTEGER DEFAULT 0 NOT NULL,
    b04_he_problemasparto TEXT DEFAULT '' NOT NULL,
    b04_he_doenzasginecologicas TEXT DEFAULT '' NOT NULL,
    b04_he_metodosbarreira TEXT DEFAULT '' NOT NULL,
    b04_he_hivela INTEGER DEFAULT 0 NOT NULL,                    -- Representa un INTEGEReano (0 = false, 1 = true)
    b04_he_hivhomem INTEGER DEFAULT 0 NOT NULL,                  -- Representa un INTEGEReano
    b04_he_serologias TEXT DEFAULT '' NOT NULL,
    b04_hme_diabete INTEGER DEFAULT 0 NOT NULL,                  -- Representa un INTEGEReano
    b04_hme_tratamientodiabete TEXT DEFAULT '' NOT NULL,
    b04_hme_hepatite INTEGER DEFAULT 0 NOT NULL,                 -- Representa un INTEGEReano
    b04_hme_tipohepatite TEXT DEFAULT '' NOT NULL,
    b04_hme_tratamientohepatite TEXT DEFAULT '' NOT NULL,
    b04_hme_hta INTEGER DEFAULT 0 NOT NULL,                      -- Representa un INTEGEReano
    b04_hme_tratamientohta TEXT DEFAULT '' NOT NULL,
    b04_hme_outrasdoenzas TEXT DEFAULT '' NOT NULL,
    b04_hme_deficiencias TEXT DEFAULT '' NOT NULL,
    b04_hme_conflictos TEXT DEFAULT '' NOT NULL,
    b04_vi_aguapotavel INTEGER DEFAULT 0 NOT NULL,               -- Representa un INTEGEReano
    b04_vi_aguatratada INTEGER DEFAULT 0 NOT NULL,               -- Representa un INTEGEReano
    b04_vi_latrina INTEGER DEFAULT 0 NOT NULL,                   -- Representa un INTEGEReano
    b04_vi_higienedomestica INTEGER DEFAULT 0 NOT NULL,          -- Representa un INTEGEReano
    b04_vi_animaisdomesticos INTEGER DEFAULT 0 NOT NULL,
    b04_vi_mosquiteirapais INTEGER DEFAULT 0 NOT NULL,           -- Representa un INTEGEReano
    b04_vi_usanamosquiteirapais INTEGER DEFAULT 0 NOT NULL,      -- Representa un INTEGEReano
    b04_vi_mosquiteiranenos INTEGER DEFAULT 0 NOT NULL,          -- Representa un INTEGEReano
    b04_vi_usanamosquiteiranenos INTEGER DEFAULT 0 NOT NULL,     -- Representa un INTEGEReano
    b04_ef_peso INTEGER DEFAULT 0 NOT NULL,
    b04_ef_altura INTEGER DEFAULT 0 NOT NULL,
    b04_ef_temperatura INTEGER DEFAULT 0 NOT NULL,
    b04_ef_perimetroabdominal INTEGER DEFAULT 0 NOT NULL,
    b04_ef_vomitos TEXT DEFAULT '' NOT NULL,
    b04_ef_posicionfetal TEXT DEFAULT '' NOT NULL,
    b04_ef_auscultacionfetal TEXT DEFAULT '' NOT NULL,
    b04_ef_alturauterinasemana INTEGER DEFAULT 0 NOT NULL,
    b04_ef_alturauterinacentimetros INTEGER DEFAULT 0 NOT NULL,
    b04_ef_leucocitosis INTEGER DEFAULT 0 NOT NULL,              -- Representa un INTEGEReano
    b04_ef_proteinuria INTEGER DEFAULT 0 NOT NULL,               -- Representa un INTEGEReano
    b04_ef_mmi INTEGER DEFAULT 0 NOT NULL,                       -- Representa un INTEGEReano
    b04_ef_cara INTEGER DEFAULT 0 NOT NULL,                      -- Representa un INTEGEReano
    b04_ef_geral INTEGER DEFAULT 0 NOT NULL,                     -- Representa un INTEGEReano
    b04_ta_data1 DATE NULL,
    b04_ta_data2 DATE NULL,
    b04_ta_data3 DATE NULL,
    b04_ta_data4 DATE NULL,
    b04_ta_data5 DATE NULL,
    b04_ta_medicamento1 TEXT DEFAULT '' NOT NULL,
    b04_ta_medicamento2 TEXT DEFAULT '' NOT NULL,
    b04_ta_medicamento3 TEXT DEFAULT '' NOT NULL,
    b04_ta_medicamento4 TEXT DEFAULT '' NOT NULL,
    b04_ta_medicamento5 TEXT DEFAULT '' NOT NULL,
    b04_ta_dose1 TEXT DEFAULT '' NOT NULL,
    b04_ta_dose2 TEXT DEFAULT '' NOT NULL,
    b04_ta_dose3 TEXT DEFAULT '' NOT NULL,
    b04_ta_dose4 TEXT DEFAULT '' NOT NULL,
    b04_ta_dose5 TEXT DEFAULT '' NOT NULL,
    b04_tda_ca_d TEXT DEFAULT '' NOT NULL,
    b04_tda_ca_m TEXT DEFAULT '' NOT NULL,
    b04_tda_ca_pd TEXT DEFAULT '' NOT NULL,
    b04_tda_vitaminac_d TEXT DEFAULT '' NOT NULL,
    b04_tda_vitaminac_m TEXT DEFAULT '' NOT NULL,
    b04_tda_vitaminac_pd TEXT DEFAULT '' NOT NULL,
    b04_tda_otrasvitaminas_d TEXT DEFAULT '' NOT NULL,
    b04_tda_otrasvitaminas_m TEXT DEFAULT '' NOT NULL,
    b04_tda_otrasvitaminas_pd TEXT DEFAULT '' NOT NULL,
    b04_tda_profilaxiamalaria_d TEXT DEFAULT '' NOT NULL,
    b04_tda_profilaxiamalaria_m TEXT DEFAULT '' NOT NULL,
    b04_tda_profilaxiamalaria_pd TEXT DEFAULT '' NOT NULL,
    CONSTRAINT pk_b04 PRIMARY KEY (b04_b01_id),
    CONSTRAINT fk_b04_b01 FOREIGN KEY (b04_b01_id) REFERENCES b01_paciente(b01_id) ON DELETE CASCADE
);

CREATE TABLE b05_historias_pediatrica (
    b05_b01_id INTEGER DEFAULT 0 NOT NULL,
    b05_alergias TEXT DEFAULT '' NOT NULL,
    b05_dataapertura DATE DEFAULT '1900-01-01' NOT NULL,
    b05_diabete INTEGER DEFAULT 0 NOT NULL,                     -- Representa un INTEGEReano (0 = false, 1 = true)
    b05_diabete_tratamento TEXT DEFAULT '' NOT NULL,
    b05_diabete_tipo TEXT DEFAULT '' NOT NULL,
    b05_hepatite INTEGER DEFAULT 0 NOT NULL,                    -- Representa un INTEGEReano
    b05_hepatite_tratamento TEXT DEFAULT '' NOT NULL,
    b05_vih INTEGER DEFAULT 0 NOT NULL,                         -- Representa un INTEGEReano
    b05_vih_tratamento TEXT DEFAULT '' NOT NULL,
    b05_outrasdoenzas TEXT DEFAULT '' NOT NULL,
    b05_conflitos TEXT DEFAULT '' NOT NULL,
    b05_profession_pai TEXT DEFAULT '' NOT NULL,
    b05_profession_mae TEXT DEFAULT '' NOT NULL,
    b05_numero_irmaos INTEGER DEFAULT 0 NOT NULL,
    b05_hn_peso INTEGER DEFAULT 0 NOT NULL,
    b05_hn_altura INTEGER DEFAULT 0 NOT NULL,
    b05_hn_semanasgestacion INTEGER DEFAULT 0 NOT NULL,
    b05_hn_apgar TEXT DEFAULT '' NOT NULL,
    b05_hn_numeroparto INTEGER DEFAULT 0 NOT NULL,
    b05_hn_incidenciasparto TEXT DEFAULT '' NOT NULL,
    b05_hn_malformaciones TEXT DEFAULT '' NOT NULL,
    b05_hn_perimetrocraniano INTEGER DEFAULT 0 NOT NULL,
    b05_hn_perimetropeito INTEGER DEFAULT 0 NOT NULL,
    b05_al_lactaciamaterna INTEGER DEFAULT 0 NOT NULL,           -- Representa un INTEGEReano
    b05_al_alimentacion_adicional TEXT DEFAULT '' NOT NULL,
    b05_al_problemasalimentacion TEXT DEFAULT '' NOT NULL,
    b05_al_agua_tratada INTEGER DEFAULT 0 NOT NULL,              -- Representa un INTEGEReano
    b05_va_bcg INTEGER DEFAULT 0 NOT NULL,                      -- Representa un INTEGEReano
    b05_va_opv0 INTEGER DEFAULT 0 NOT NULL,                     -- Representa un INTEGEReano
    b05_va_opv1 INTEGER DEFAULT 0 NOT NULL,                     -- Representa un INTEGEReano
    b05_va_opv2 INTEGER DEFAULT 0 NOT NULL,                     -- Representa un INTEGEReano
    b05_va_opv3 INTEGER DEFAULT 0 NOT NULL,                     -- Representa un INTEGEReano
    b05_va_dpthib1 INTEGER DEFAULT 0 NOT NULL,                  -- Representa un INTEGEReano
    b05_va_dpthib2 INTEGER DEFAULT 0 NOT NULL,                  -- Representa un INTEGEReano
    b05_va_dpthib3 INTEGER DEFAULT 0 NOT NULL,                  -- Representa un INTEGEReano
    b05_va_hepb1 INTEGER DEFAULT 0 NOT NULL,                    -- Representa un INTEGEReano
    b05_va_hepb2 INTEGER DEFAULT 0 NOT NULL,                    -- Representa un INTEGEReano
    b05_va_hepb3 INTEGER DEFAULT 0 NOT NULL,                    -- Representa un INTEGEReano
    b05_va_sarampo9 INTEGER DEFAULT 0 NOT NULL,                 -- Representa un INTEGEReano
    b05_va_sarampo10 INTEGER DEFAULT 0 NOT NULL,                -- Representa un INTEGEReano
    b05_e_aguapotavel INTEGER DEFAULT 0 NOT NULL,               -- Representa un INTEGEReano
    b05_e_latrina INTEGER DEFAULT 0 NOT NULL,                   -- Representa un INTEGEReano
    b05_e_higienedomestica INTEGER DEFAULT 0 NOT NULL,          -- Representa un INTEGEReano
    b05_e_mosquiteira INTEGER DEFAULT 0 NOT NULL,               -- Representa un INTEGEReano
    b05_e_usana INTEGER DEFAULT 0 NOT NULL,                     -- Representa un INTEGEReano
    b05_e_animaisdomesticos INTEGER DEFAULT 0 NOT NULL,
    b05_ta_data1 DATE NULL,
    b05_ta_medicamento1 TEXT DEFAULT '' NOT NULL,
    b05_ta_dose1 TEXT DEFAULT '' NOT NULL,
    b05_ta_data2 DATE NULL,
    b05_ta_medicamento2 TEXT DEFAULT '' NOT NULL,
    b05_ta_dose2 TEXT DEFAULT '' NOT NULL,
    b05_ta_data3 DATE NULL,
    b05_ta_medicamento3 TEXT DEFAULT '' NOT NULL,
    b05_ta_dose3 TEXT DEFAULT '' NOT NULL,
    b05_ta_data4 DATE NULL,
    b05_ta_medicamento4 TEXT DEFAULT '' NOT NULL,
    b05_ta_dose4 TEXT DEFAULT '' NOT NULL,
    b05_hc_tipodoenza TEXT DEFAULT '' NOT NULL,
    b05_hc_tratamientodoenza TEXT DEFAULT '' NOT NULL,
    b05_e_situacioneconomica TEXT DEFAULT '' NOT NULL,
    b05_al_aguatratadacon TEXT DEFAULT '' NOT NULL,
    b05_ta_tratamiento1 INTEGER DEFAULT 0 NOT NULL,
    b05_ta_tratamiento2 INTEGER DEFAULT 0 NOT NULL,
    b05_ta_tratamiento3 INTEGER DEFAULT 0 NOT NULL,
    b05_ta_tratamiento4 INTEGER DEFAULT 0 NOT NULL,
    CONSTRAINT pk_b05 PRIMARY KEY (b05_b01_id),
    CONSTRAINT fk_b05_b01 FOREIGN KEY (b05_b01_id) REFERENCES b01_paciente(b01_id) ON DELETE CASCADE
);

CREATE TABLE b06_consultas_adulto (
    b06_b01_id INTEGER NOT NULL DEFAULT 0,
    b06_fecha TIMESTAMP NOT NULL DEFAULT '1900-01-01 00:00:00',
    b06_motivo TEXT NOT NULL DEFAULT '',
    b06_ef_agitacionnasal INTEGER NOT NULL DEFAULT 0,
    b06_ef_estridor INTEGER NOT NULL DEFAULT 0,
    b06_ef_sibilos INTEGER NOT NULL DEFAULT 0,
    b06_ef_tiraje INTEGER NOT NULL DEFAULT 0,
    b06_ef_arritmia INTEGER NOT NULL DEFAULT 0,
    b06_ef_enchimentocapilar INTEGER NOT NULL DEFAULT 0,
    b06_ef_ausenciapulso INTEGER NOT NULL DEFAULT 0,
    b06_ef_edemas INTEGER NOT NULL DEFAULT 0,
    b06_ef_pregadapele INTEGER NOT NULL DEFAULT 0,
    b06_ef_mucosaspalidas INTEGER NOT NULL DEFAULT 0,
    b06_ef_enoftalmia INTEGER NOT NULL DEFAULT 0,
    b06_ef_palmamaobranca INTEGER NOT NULL DEFAULT 0,
    b06_ef_megalia INTEGER NOT NULL DEFAULT 0,
    b06_ef_megaliadescripcion TEXT NOT NULL DEFAULT '',
    b06_ef_adenopatias INTEGER NOT NULL DEFAULT 0,
    b06_ef_adenopatiasdescripcion TEXT NOT NULL DEFAULT '',
    b06_ef_secrecion INTEGER NOT NULL DEFAULT 0,
    b06_ef_alteracionheces INTEGER NOT NULL DEFAULT 0,
    b06_ef_tosse INTEGER NOT NULL DEFAULT 0,
    b06_ef_tossedescripcion TEXT NOT NULL DEFAULT '',
    b06_ef_alteracionurina INTEGER NOT NULL DEFAULT 0,
    b06_ef_alteracionurinadescripcion TEXT NOT NULL DEFAULT '',
    b06_ef_vomitos INTEGER NOT NULL DEFAULT 0,
    b06_ef_gradodeshidratacion TEXT NOT NULL DEFAULT '',
    b06_ef_gradosubnutricion TEXT NOT NULL DEFAULT '',
    b06_ef_outros TEXT NOT NULL DEFAULT '',
    b06_ef_irritable INTEGER NOT NULL DEFAULT 0,
    b06_ef_codutaoutro TEXT NOT NULL DEFAULT '',
    b06_le_region1 INTEGER NOT NULL DEFAULT 0,
    b06_le_region2 INTEGER NOT NULL DEFAULT 0,
    b06_le_region3 INTEGER NOT NULL DEFAULT 0,
    b06_le_region4 INTEGER NOT NULL DEFAULT 0,
    b06_le_region5 INTEGER NOT NULL DEFAULT 0,
    b06_le_region6 INTEGER NOT NULL DEFAULT 0,
    b06_le_region7 INTEGER NOT NULL DEFAULT 0,
    b06_le_region8 INTEGER NOT NULL DEFAULT 0,
    b06_le_prejuizo1 TEXT NOT NULL DEFAULT '',
    b06_le_prejuizo2 TEXT NOT NULL DEFAULT '',
    b06_le_prejuizo3 TEXT NOT NULL DEFAULT '',
    b06_le_prejuizo4 TEXT NOT NULL DEFAULT '',
    b06_le_prejuizo5 TEXT NOT NULL DEFAULT '',
    b06_le_prejuizo6 TEXT NOT NULL DEFAULT '',
    b06_le_prejuizo7 TEXT NOT NULL DEFAULT '',
    b06_le_prejuizo8 TEXT NOT NULL DEFAULT '',
    CONSTRAINT pk_b06 PRIMARY KEY (b06_b01_id, b06_fecha),
    CONSTRAINT fk_b06_b03 FOREIGN KEY (b06_b01_id) REFERENCES b03_historias_adulto(b03_b01_id) ON DELETE CASCADE
);

CREATE TABLE b07_consultas_embarazada (
    b07_b01_id INTEGER NOT NULL DEFAULT 0,
    b07_fecha TIMESTAMP NOT NULL DEFAULT '1900-01-01 00:00:00',
    b07_motivo TEXT NOT NULL DEFAULT '',
    b07_ef_peso INTEGER NOT NULL DEFAULT 0,
    b07_ef_altura INTEGER NOT NULL DEFAULT 0,
    b07_ef_temperatura INTEGER NOT NULL DEFAULT 0,
    b07_ef_perimetroabdominal INTEGER NOT NULL DEFAULT 0,
    b07_ef_vomitos TEXT NOT NULL DEFAULT '',
    b07_ef_posicionfetal TEXT NOT NULL DEFAULT '',
    b07_ef_auscultacionfetal TEXT NOT NULL DEFAULT '',
    b07_ef_alturauterinasemana INTEGER NOT NULL DEFAULT 0,
    b07_ef_alturauterinacentimetros INTEGER NOT NULL DEFAULT 0,
    b07_ef_leucocitosis INTEGER NOT NULL DEFAULT 0,
    b07_ef_proteinuria INTEGER NOT NULL DEFAULT 0,
    b07_ef_mmi INTEGER NOT NULL DEFAULT 0,
    b07_ef_cara INTEGER NOT NULL DEFAULT 0,
    b07_ef_geral INTEGER NOT NULL DEFAULT 0,
    b07_tda_ca_d TEXT NOT NULL DEFAULT '',
    b07_tda_ca_m TEXT NOT NULL DEFAULT '',
    b07_tda_ca_pd TEXT NOT NULL DEFAULT '',
    b07_tda_vitaminac_d TEXT NOT NULL DEFAULT '',
    b07_tda_vitaminac_m TEXT NOT NULL DEFAULT '',
    b07_tda_vitaminac_pd TEXT NOT NULL DEFAULT '',
    b07_tda_otrasvitaminas_d TEXT NOT NULL DEFAULT '',
    b07_tda_otrasvitaminas_m TEXT NOT NULL DEFAULT '',
    b07_tda_otrasvitaminas_pd TEXT NOT NULL DEFAULT '',
    b07_tda_profilaxiamalaria_d TEXT NOT NULL DEFAULT '',
    b07_tda_profilaxiamalaria_m TEXT NOT NULL DEFAULT '',
    b07_tda_profilaxiamalaria_pd TEXT NOT NULL DEFAULT '',
    CONSTRAINT pk_b07 PRIMARY KEY (b07_b01_id, b07_fecha),
    CONSTRAINT fk_b07_b04 FOREIGN KEY (b07_b01_id) REFERENCES b04_historias_embarazada(b04_b01_id) ON DELETE CASCADE
);


CREATE TABLE b08_consultas_pediatrica (
	b08_b01_id INTEGER DEFAULT 0 NOT NULL,
	b08_dataconsulta TIMESTAMP NOT NULL DEFAULT '1900-01-01 00:00:00',
	b08_motivo TEXT DEFAULT '' NOT NULL,
	b08_ef_agitacionnasal INTEGER DEFAULT 0 NOT NULL,
	b08_ef_estridor INTEGER DEFAULT 0 NOT NULL,
	b08_ef_sibilos INTEGER DEFAULT 0 NOT NULL,
	b08_ef_tiraje INTEGER DEFAULT 0 NOT NULL,
	b08_ef_arritmia INTEGER DEFAULT 0 NOT NULL,
	b08_ef_enchimentocapilar INTEGER DEFAULT 0 NOT NULL,
	b08_ef_ausenciapulso INTEGER DEFAULT 0 NOT NULL,
	b08_ef_pregadapele INTEGER DEFAULT 0 NOT NULL,
	b08_ef_mucosaspalidas INTEGER DEFAULT 0 NOT NULL,
	b08_ef_enoftalmia INTEGER DEFAULT 0 NOT NULL,
	b08_ef_palmamaobranca INTEGER DEFAULT 0 NOT NULL,
	b08_ef_megalia INTEGER DEFAULT 0 NOT NULL,
	b08_ef_megaliadescripcion TEXT DEFAULT '' NOT NULL,
	b08_ef_adenopatias INTEGER DEFAULT 0 NOT NULL,
	b08_ef_adenopatiasdescripcion TEXT DEFAULT '' NOT NULL,
	b08_ef_secrecion INTEGER DEFAULT 0 NOT NULL,
	b08_ef_alteracionheces INTEGER DEFAULT 0 NOT NULL,
	b08_ef_tosse INTEGER DEFAULT 0 NOT NULL,
	b08_ef_tossedescripcion TEXT DEFAULT '' NOT NULL,
	b08_ef_alteracionurina INTEGER DEFAULT 0 NOT NULL,
	b08_ef_alteracionurinadescripcion TEXT DEFAULT '' NOT NULL,
	b08_ef_vomitos INTEGER DEFAULT 0 NOT NULL,
	b08_ef_gradodeshidratacion TEXT DEFAULT '' NOT NULL,
	b08_ef_gradosubnutricion TEXT DEFAULT '' NOT NULL,
	b08_ef_outros TEXT DEFAULT '' NOT NULL,
	b08_ef_peso INTEGER DEFAULT 0 NOT NULL,
	b08_ef_talla INTEGER DEFAULT 0 NOT NULL,
	b08_ef_temperatura INTEGER DEFAULT 0 NOT NULL,
	b08_ef_perimetrobraquial INTEGER DEFAULT 0 NOT NULL,
	b08_ef_glucemia INTEGER DEFAULT 0 NOT NULL,
	b08_ef_fc TEXT DEFAULT '' NOT NULL,
	b08_ef_fr TEXT DEFAULT '' NOT NULL,
	b08_ef_consciencia TEXT DEFAULT '' NOT NULL,
	b08_ta_ca_d TEXT DEFAULT '' NOT NULL,
	b08_ta_ca_m TEXT DEFAULT '' NOT NULL,
	b08_ta_ca_pd TEXT DEFAULT '' NOT NULL,
	b08_ta_fe_d TEXT DEFAULT '' NOT NULL,
	b08_ta_fe_m TEXT DEFAULT '' NOT NULL,
	b08_ta_fe_pd TEXT DEFAULT '' NOT NULL,
	b08_ta_acidofolico_d TEXT DEFAULT '' NOT NULL,
	b08_ta_acidofolico_m TEXT DEFAULT '' NOT NULL,
	b08_ta_acidofolico_pd TEXT DEFAULT '' NOT NULL,
	b08_ta_desparasitacion_d TEXT DEFAULT '' NOT NULL,
	b08_ta_desparasitacion_m TEXT DEFAULT '' NOT NULL,
	b08_ta_desparasitacion_pd TEXT DEFAULT '' NOT NULL,
	b08_ta_vitaminac_d TEXT DEFAULT '' NOT NULL,
	b08_ta_vitaminac_m TEXT DEFAULT '' NOT NULL,
	b08_ta_vitaminac_pd TEXT DEFAULT '' NOT NULL,
	b08_ta_otrasvitaminas_d TEXT DEFAULT '' NOT NULL,
	b08_ta_otrasvitaminas_m TEXT DEFAULT '' NOT NULL,
	b08_ta_otrasvitaminas_pd TEXT DEFAULT '' NOT NULL,
	b08_ta_profilaxiamalaria_d TEXT DEFAULT '' NOT NULL,
	b08_ta_profilaxiamalaria_m TEXT DEFAULT '' NOT NULL,
	b08_ta_profilaxiamalaria_pd TEXT DEFAULT '' NOT NULL,
	b08_le_region1 INTEGER DEFAULT 0 NOT NULL,
	b08_le_region2 INTEGER DEFAULT 0 NOT NULL,
	b08_le_region3 INTEGER DEFAULT 0 NOT NULL,
	b08_le_region4 INTEGER DEFAULT 0 NOT NULL,
	b08_le_region5 INTEGER DEFAULT 0 NOT NULL,
	b08_le_region6 INTEGER DEFAULT 0 NOT NULL,
	b08_le_region7 INTEGER DEFAULT 0 NOT NULL,
	b08_le_region8 INTEGER DEFAULT 0 NOT NULL,
	b08_le_prejuizo1 TEXT DEFAULT '' NOT NULL,
	b08_le_prejuizo2 TEXT DEFAULT '' NOT NULL,
	b08_le_prejuizo3 TEXT DEFAULT '' NOT NULL,
	b08_le_prejuizo4 TEXT DEFAULT '' NOT NULL,
	b08_le_prejuizo5 TEXT DEFAULT '' NOT NULL,
	b08_le_prejuizo6 TEXT DEFAULT '' NOT NULL,
	b08_le_prejuizo7 TEXT DEFAULT '' NOT NULL,
	b08_le_prejuizo8 TEXT DEFAULT '' NOT NULL,
	b08_ef_consciencia_combo INTEGER DEFAULT 0 NOT NULL,
	b08_ef_estado_mental INTEGER DEFAULT 0 NOT NULL,
	b08_ef_brazo_cor INTEGER DEFAULT 0 NOT NULL,
	b08_ef_test_apetito INTEGER DEFAULT 0 NOT NULL,
	b08_ef_test_malaria INTEGER DEFAULT 0 NOT NULL,
	b08_ef_relacion_peso INTEGER DEFAULT 0 NOT NULL,
	b08_ef_relacion_altura INTEGER DEFAULT 0 NOT NULL,
	b08_ef_bradipnea INTEGER DEFAULT 0 NOT NULL,
	b08_ef_conulsao INTEGER DEFAULT 0 NOT NULL,
	b08_ef_beber_comer INTEGER DEFAULT 0 NOT NULL,
	b08_ef_rp_tiraje_tipo INTEGER DEFAULT 0 NOT NULL,
	b08_ef_rp_tiraje_severidad INTEGER DEFAULT 0 NOT NULL,
	b08_ef_rp_taquipneia INTEGER DEFAULT 0 NOT NULL,
	b08_ef_rp_estridor INTEGER DEFAULT 0 NOT NULL,
	b08_ef_rp_chiado INTEGER DEFAULT 0 NOT NULL,
	b08_ef_rp_secrecoes INTEGER DEFAULT 0 NOT NULL,
	b08_ef_rp_tempo INTEGER DEFAULT 0 NOT NULL,
	b08_ef_rp_queimacoe INTEGER DEFAULT 0 NOT NULL,
	b08_ef_rp_grunhido INTEGER DEFAULT 0 NOT NULL,
	b08_ef_rp_narizpingar INTEGER DEFAULT 0 NOT NULL,
	b08_ef_rp_dorgarganta INTEGER DEFAULT 0 NOT NULL,
	b08_ef_rp_congestionamento INTEGER DEFAULT 0 NOT NULL,
	b08_ef_rp_lagrimeo INTEGER DEFAULT 0 NOT NULL,
	b08_ef_rp_saturacion_oxigeno INTEGER DEFAULT 0 NOT NULL,
	b08_ef_el_heces INTEGER DEFAULT 0 NOT NULL,
	b08_ef_el_urina INTEGER DEFAULT 0 NOT NULL,
	b08_ef_el_vomitos INTEGER DEFAULT 0 NOT NULL,
	b08_ef_el_sangramento TEXT DEFAULT '' NOT NULL,
	b08_ef_cc_enchimento_capilar INTEGER DEFAULT 0 NOT NULL,
	b08_ef_cc_cianose INTEGER DEFAULT 0 NOT NULL,
	b08_ef_cc_edemas TEXT DEFAULT '' NOT NULL,
	b08_ef_cc_arritmia TEXT DEFAULT '' NOT NULL,
	b08_ef_cc_fc INTEGER DEFAULT 0 NOT NULL,
	b08_ef_pm_pel_seca INTEGER DEFAULT 0 NOT NULL,
	b08_ef_pm_petequias INTEGER DEFAULT 0 NOT NULL,
	b08_ef_pm_pustulas INTEGER DEFAULT 0 NOT NULL,
	b08_ef_pm_ictericia INTEGER DEFAULT 0 NOT NULL,
	b08_ef_pm_exantema INTEGER DEFAULT 0 NOT NULL,
	b08_ef_pm_infeccao INTEGER DEFAULT 0 NOT NULL,
	b08_ef_pm_edema INTEGER DEFAULT 0 NOT NULL,
	b08_ef_ol_secrecao INTEGER DEFAULT 0 NOT NULL,
	b08_ef_ol_edema_parpado INTEGER DEFAULT 0 NOT NULL,
	b08_ef_ol_parpados_pegados INTEGER DEFAULT 0 NOT NULL,
	b08_ef_ol_conjuntiva_vermelha INTEGER DEFAULT 0 NOT NULL,
	b08_ef_ol_conjuntiva_branca INTEGER DEFAULT 0 NOT NULL,
	b08_ef_pm_lesiones_corpo TEXT DEFAULT '' NOT NULL,
	b08_ef_oi_inchacao_atras_orella INTEGER DEFAULT 0 NOT NULL,
	b08_ef_oi_prurito_conducto_auditivo INTEGER DEFAULT 0 NOT NULL,
	b08_ef_oi_dor INTEGER DEFAULT 0 NOT NULL,
	b08_ef_oi_secrecao INTEGER DEFAULT 0 NOT NULL,
	b08_ef_oi_otoscopia_timpano INTEGER DEFAULT 0 NOT NULL,
	b08_ef_bc_manchas_koplit INTEGER DEFAULT 0 NOT NULL,
	b08_ef_bc_pracas_brancas INTEGER DEFAULT 0 NOT NULL,
	b08_ef_bc_lingua_roja INTEGER DEFAULT 0 NOT NULL,
	b08_ef_bc_petequias_paladar INTEGER DEFAULT 0 NOT NULL,
	b08_ef_bc_ganglios_pescozo INTEGER DEFAULT 0 NOT NULL,
	b08_ef_bc_amigdalas_eritematosas INTEGER DEFAULT 0 NOT NULL,
	b08_ef_bc_dor_boca INTEGER DEFAULT 0 NOT NULL,
	b08_ef_bc_lesoes_tipo TEXT DEFAULT '' NOT NULL,
	b08_ef_ad_signos_dor INTEGER DEFAULT 0 NOT NULL,
	b08_ef_ne_cefalea_intensa INTEGER DEFAULT 0 NOT NULL,
	b08_ef_ne_fotofobia INTEGER DEFAULT 0 NOT NULL,
	b08_ef_ne_signo_brudzinski INTEGER DEFAULT 0 NOT NULL,
	b08_ef_ne_signo_kerning INTEGER DEFAULT 0 NOT NULL,
	b08_ef_ne_nuca_rigida INTEGER DEFAULT 0 NOT NULL,
	b08_ef_ne_fontanela_abombada INTEGER DEFAULT 0 NOT NULL,
	b08_ef_ne_problemas_desarrollo INTEGER DEFAULT 0 NOT NULL,
	b08_ef_ne_problemas_desarrollo_desc TEXT DEFAULT '' NOT NULL,
	b08_ef_ed_hambre_exagerada INTEGER DEFAULT 0 NOT NULL,
	b08_ef_ed_astenia INTEGER DEFAULT 0 NOT NULL,
	b08_ef_ed_sed_exagerada INTEGER DEFAULT 0 NOT NULL,
	b08_ef_ed_adenopatias TEXT DEFAULT '' NOT NULL,
	b08_ef_ed_perdida_peso_rapido TEXT DEFAULT '' NOT NULL,
	b08_ef_ed_olor_aliento TEXT DEFAULT '' NOT NULL,
	b08_diagnostico_enfermeria INTEGER DEFAULT 0 NOT NULL,
	b08_otro_diagnostico TEXT DEFAULT '' NOT NULL,
	b08_recomendacion1 INTEGER DEFAULT 0 NOT NULL,
	b08_recomendacion2 INTEGER DEFAULT 0 NOT NULL,
	b08_recomendacion3 INTEGER DEFAULT 0 NOT NULL,
	b08_recomendacion4 INTEGER DEFAULT 0 NOT NULL,
	b08_recomendacion5 INTEGER DEFAULT 0 NOT NULL,
	b08_tt_pa1 INTEGER DEFAULT 0 NOT NULL,
	b08_tt_pa2 INTEGER DEFAULT 0 NOT NULL,
	b08_tt_pa3 INTEGER DEFAULT 0 NOT NULL,
	b08_tt_pa4 INTEGER DEFAULT 0 NOT NULL,
	b08_tt_pa5 INTEGER DEFAULT 0 NOT NULL,
	b08_tt_pa6 INTEGER DEFAULT 0 NOT NULL,
	b08_tt_pa7 INTEGER DEFAULT 0 NOT NULL,
	b08_tt_pa8 INTEGER DEFAULT 0 NOT NULL,
	b08_tt_pa9 INTEGER DEFAULT 0 NOT NULL,
	b08_tt_pa10 INTEGER DEFAULT 0 NOT NULL,
	b08_tt_descripcion1 TEXT DEFAULT '' NOT NULL,
	b08_tt_descripcion2 TEXT DEFAULT '' NOT NULL,
	b08_tt_descripcion3 TEXT DEFAULT '' NOT NULL,
	b08_tt_descripcion4 TEXT DEFAULT '' NOT NULL,
	b08_tt_descripcion5 TEXT DEFAULT '' NOT NULL,
	b08_tt_descripcion6 TEXT DEFAULT '' NOT NULL,
	b08_tt_descripcion7 TEXT DEFAULT '' NOT NULL,
	b08_tt_descripcion8 TEXT DEFAULT '' NOT NULL,
	b08_tt_descripcion9 TEXT DEFAULT '' NOT NULL,
	b08_tt_descripcion10 TEXT DEFAULT '' NOT NULL,
	b08_tt_via1 INTEGER DEFAULT 0 NOT NULL,
	b08_tt_via2 INTEGER DEFAULT 0 NOT NULL,
	b08_tt_via3 INTEGER DEFAULT 0 NOT NULL,
	b08_tt_via4 INTEGER DEFAULT 0 NOT NULL,
	b08_tt_via5 INTEGER DEFAULT 0 NOT NULL,
	b08_tt_via6 INTEGER DEFAULT 0 NOT NULL,
	b08_tt_via7 INTEGER DEFAULT 0 NOT NULL,
	b08_tt_via8 INTEGER DEFAULT 0 NOT NULL,
	b08_tt_via9 INTEGER DEFAULT 0 NOT NULL,
	b08_tt_via10 INTEGER DEFAULT 0 NOT NULL,
	b08_tt_dias1 INTEGER DEFAULT 0 NOT NULL,
	b08_tt_dias2 INTEGER DEFAULT 0 NOT NULL,
	b08_tt_dias3 INTEGER DEFAULT 0 NOT NULL,
	b08_tt_dias4 INTEGER DEFAULT 0 NOT NULL,
	b08_tt_dias5 INTEGER DEFAULT 0 NOT NULL,
	b08_tt_dias6 INTEGER DEFAULT 0 NOT NULL,
	b08_tt_dias7 INTEGER DEFAULT 0 NOT NULL,
	b08_tt_dias8 INTEGER DEFAULT 0 NOT NULL,
	b08_tt_dias9 INTEGER DEFAULT 0 NOT NULL,
	b08_tt_dias10 INTEGER DEFAULT 0 NOT NULL,
	b08_tt_dosis1 TEXT DEFAULT '' NOT NULL,
	b08_tt_dosis2 TEXT DEFAULT '' NOT NULL,
	b08_tt_dosis3 TEXT DEFAULT '' NOT NULL,
	b08_tt_dosis4 TEXT DEFAULT '' NOT NULL,
	b08_tt_dosis5 TEXT DEFAULT '' NOT NULL,
	b08_tt_dosis6 TEXT DEFAULT '' NOT NULL,
	b08_tt_dosis7 TEXT DEFAULT '' NOT NULL,
	b08_tt_dosis8 TEXT DEFAULT '' NOT NULL,
	b08_tt_dosis9 TEXT DEFAULT '' NOT NULL,
	b08_tt_dosis10 TEXT DEFAULT '' NOT NULL,
	b08_tt_frecuencia1 TEXT DEFAULT '' NOT NULL,
	b08_tt_frecuencia2 TEXT DEFAULT '' NOT NULL,
	b08_tt_frecuencia3 TEXT DEFAULT '' NOT NULL,
	b08_tt_frecuencia4 TEXT DEFAULT '' NOT NULL,
	b08_tt_frecuencia5 TEXT DEFAULT '' NOT NULL,
	b08_tt_frecuencia6 TEXT DEFAULT '' NOT NULL,
	b08_tt_frecuencia7 TEXT DEFAULT '' NOT NULL,
	b08_tt_frecuencia8 TEXT DEFAULT '' NOT NULL,
	b08_tt_frecuencia9 TEXT DEFAULT '' NOT NULL,
	b08_tt_frecuencia10 TEXT DEFAULT '' NOT NULL,
	b08_tt_perfusion1 INTEGER DEFAULT 0 NOT NULL,
	b08_tt_perfusion2 INTEGER DEFAULT 0 NOT NULL,
	b08_tt_perfusion3 INTEGER DEFAULT 0 NOT NULL,
	b08_tt_perfusion4 INTEGER DEFAULT 0 NOT NULL,
	b08_tt_perfusion5 INTEGER DEFAULT 0 NOT NULL,
	b08_tt_perfusion6 INTEGER DEFAULT 0 NOT NULL,
	b08_tt_perfusion7 INTEGER DEFAULT 0 NOT NULL,
	b08_tt_perfusion8 INTEGER DEFAULT 0 NOT NULL,
	b08_tt_perfusion9 INTEGER DEFAULT 0 NOT NULL,
	b08_tt_perfusion10 INTEGER DEFAULT 0 NOT NULL,
	CONSTRAINT pk_b08 CONSTRAINT pk_b08 PRIMARY KEY (b08_b01_id, b08_dataconsulta),
	CONSTRAINT fk_b08_b05 FOREIGN KEY (b08_b01_id) REFERENCES b05_historias_pediatrica(b05_b01_id) ON DELETE CASCADE
);

